/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_whitboxwithjni_WhiteBox */

#ifndef _Included_com_example_whitboxwithjni_WhiteBox
#define _Included_com_example_whitboxwithjni_WhiteBox
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_whitboxwithjni_WhiteBox
 * Method:    encrypt
 * Signature: ()V
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_whitboxwithjni_WhiteBox_encrypt
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_example_whitboxwithjni_WhiteBox
 * Method:    decrypt
 * Signature: ()V
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_whitboxwithjni_WhiteBox_decrypt
  (JNIEnv *, jobject, jstring, jstring);


#ifdef __cplusplus
}
#endif
#endif
